"""use_json_for_list_columns

Revision ID: 1012edbce3a0
Revises: 0d1b3498a20e
Create Date: 2026-04-22 22:40:15.049651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1012edbce3a0'
down_revision: Union[str, None] = '0d1b3498a20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE interactions ALTER COLUMN attendees TYPE JSON USING array_to_json(attendees)')
    op.execute('ALTER TABLE interactions ALTER COLUMN materials_shared TYPE JSON USING array_to_json(materials_shared)')
    op.execute('ALTER TABLE interactions ALTER COLUMN samples_distributed TYPE JSON USING array_to_json(samples_distributed)')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE interactions ALTER COLUMN samples_distributed TYPE VARCHAR[] USING array(select jsonb_array_elements_text(samples_distributed))')
    op.execute('ALTER TABLE interactions ALTER COLUMN materials_shared TYPE VARCHAR[] USING array(select jsonb_array_elements_text(materials_shared))')
    op.execute('ALTER TABLE interactions ALTER COLUMN attendees TYPE VARCHAR[] USING array(select jsonb_array_elements_text(attendees))')
    # ### end Alembic commands ###
