"""fix_nullable_time_and_followup_date

Revision ID: 1d0bdf153ac7
Revises: 0d1b3498a20e
Create Date: 2026-04-22 22:35:46.528204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0bdf153ac7'
down_revision: Union[str, None] = '0d1b3498a20e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
